### ISSUE TITLE
sftp isn't working

### ISSUE THREAD

**Issue by GER-EDDM** [matthewwall/weewx-sftp#11]
The Upload of the weather data has worked fine since two weeks. Yesterday between 22:00 and 22:05 some settings must be changed by itself because a upload is not possible.
I haven't changed anything. Can anyone tell me what I can do to fix the problem?

The error:

 Mai 13 01:36:06 raspberrypi weewx[15975]: **** File "/usr/local/lib/python2.7/dist-packages/pysftp/__init__.py", line 143, in __init__
Mai 13 01:36:06 raspberrypi weewx[15975]: **** self._transport.connect(**self._tconnect)
Mai 13 01:36:06 raspberrypi weewx[15975]: **** File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 1263, in connect
Mai 13 01:36:06 raspberrypi weewx[15975]: **** self.auth_password(username, password)
Mai 13 01:36:06 raspberrypi weewx[15975]: **** File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 1436, in auth_password
Mai 13 01:36:06 raspberrypi weewx[15975]: **** return self.auth_handler.wait_for_response(my_event)
Mai 13 01:36:06 raspberrypi weewx[15975]: **** File "/usr/local/lib/python2.7/dist-packages/paramiko/auth_handler.py", line 240, in wait_for_response
Mai 13 01:36:06 raspberrypi weewx[15975]: **** raise AuthenticationException("Authentication timeout.")
Mai 13 01:36:06 raspberrypi weewx[15975]: **** AuthenticationException: Authentication timeout.
Mai 13 01:36:06 raspberrypi weewx[15975]: **** Generator terminated

**Comment by matthewwall** [comment]
can you make the sftp connection using some other client?

*something* must have changed, whether it was a change to your configuration file, and change to your .ssh configuration, expiration of your credentials on the server, or who knows?

try connecting manually with an sftp client
