### ISSUE TITLE
readme file improvement proposal

### ISSUE THREAD

**Issue by bonjour81** [matthewwall/weewx-sftp#2]
Hello Matthew,

I would like to point out a few issues I found while installing sftp addon.
It may be just a few little of modification to make it easier if you are interested.

1/ When installed, the weewx.conf file show for password:
`password = '"replace_me"'`
This was a bit confusing, because unlike other fields, there was those '"..."'
I though it was on purpose, but if you keep those, it does not work.   
I would suggest:
`password = replace_me`

2/ it is missing local directory, ex:
`local_root = /var/www/html/weewx`
work fine after adding this line (I use  /var/www/html/weewx/www for uploaded files)

3/ I had an issue with the remote directory:
on my remote server (an internet hosting service) the webdata are in a subdirectory "www"
so I first set:
`path = /www/ `   (like on my previous ftp settings) => not working
then I set :
`path = /www `   (following your readme file with /weewx example) => not working
finally this is working:
`path = www`  

4/ I'm not 100% but it seems default port for sftp is 22  (filezilla use port 22 if port is not specified, and my hosting service use port 22 too).
but it looks like the skin use port 2222 as default (if not specified in weewx.conf).

**Comment by bonjour81** [comment]
Hi again, sorry, infact "local_root" does not work.
if I add 
`local_root = /var/www/html/weewx/www` it will anyway upload default directory:
`/var/www/html/weewx`

**Comment by bonjour81** [comment]
#3 
I added a pull request with a proposal (but missed how to link issue & PR :( ).

**Comment by matthewwall** [comment]
the local_root is specified using the standard HTML_ROOT and WEEWX_ROOT variables (see the report documentation in the weewx customization guide)

issues have been addressed in commit b105537

**Comment by bonjour81** [comment]
AAh agreed, I modified to use HTML_ROOT inside the `[[sftp]]` to specify the path I want to upload.It works fine.
Sorry for this!
Maybe it could be added to readme file: that's why I didn't though about it.
